services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=dpg-d80s3djeo5us73fr8mmg-a.frankfurt-postgres.render.com;Port=5432;Database=inzdb_jdmh;Username=postgresuser;Password=wFXuVDdaN3GZYnAJBLay9m9NTyFfYNYn