<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>Inzynierka.Domain</PackageId>
	<Version>1.0.0</Version>
	<Authors>Kacper Sojda</Authors>
	<Description>Modele domenowe dla systemu chatu.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>

</Project>
